plugins:
  - jekyll-seo-tag


url: "https://kunqian-58.github.io"
baseurl: ""

# If you are building a GitHub project page then use these settings:
#url: "http://username.github.io/projectname"
#baseurl: "/projectname"

# Of course don't forget to change the username and projectname to YOUR username and project

# Name of website
title: Kun Qian homepage, research page, Kun Qian's personal website

# Short description of your site
description: Kun Qian's personal website. Kun Qian is a researcher at IBM Research AI, and a former student at University of California Santa Cruz (UCSC), and a researcher working on human-in-the-loop machine learning and active learning for knowledge creation.

author: Kun Qian
